services:
  mysql-db:
    image: mysql:8.4.4
    restart: always
    environment:
      - MYSQL_DATABASE=messages
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3306:3306'
    volumes:
      - type: bind
        source: volumes/mysql/db
        target: /var/lib/mysql
      - type: bind
        source: volumes/mysql/init.sql
        target: /docker-entrypoint-initdb.d/init.sql