services:
  mysql-db:
    image: mysql:8.4.4
    environment:
      - MYSQL_DATABASE=messages
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - 3306:3306
    volumes:
      - type: bind
        source: ../volumes/database/db
        target: /var/lib/mysql
      - type: bind
        source: ../volumes/database/init.sql
        target: /docker-entrypoint-initdb.d/init.sql