site_name: SQS-Messanger - Dokumentation
docs_dir: pages
nav:
  - Start: index.md
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
  icon:
    admonition:
      alert: material/alert-circle 
markdown_extensions:
  - toc
  - tables
  - admonition
