site_name: SQS-Messanger - Dokumentation
docs_dir: pages
nav:
  - Start: index.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Arc42: arc42.md
  - API: api.md
  - External API: external_api.md
  - License: license.md
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
  icon:
    admonition:
      alert: material/alert-circle 
markdown_extensions:
  - toc
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
