site_name: SQS-Messanger - Dokumentation
docs_dir: pages
nav:
  - Start: pages/index.md
  - Introduction: pages/introduction.md
  - Installation: pages/installation.md
  - Arc42: pages/ac42/arc42.md
  - API: pages/api.md
  - External API: pages/external_api.md
  - License: pages/license.md
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
  icon:
    admonition:
      alert: material/alert-circle 
markdown_extensions:
  - toc
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences