name: CI-Pipeline

on:
  push:

jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Permissions
        run: chmod +x sqsbackend/gradlew 
        
      - name: Build with Gradle
        run: ./sqsbackend/gradlew build -p sqsbackend/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: sqsbackend/build/libs

  run-unit-tests:
    name: Run unit tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Permissions
        run: chmod +x sqsbackend/gradlew
          
      - name: Run unit tests
        run: ./sqsbackend/gradlew test -p sqsbackend/
        
  create-jacoco-report:
    name: Create jacoco report
    needs: run-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Permissions
        run: chmod +x sqsbackend/gradlew
          
      - name: Run unit tests
        run: ./sqsbackend/gradlew jacocoTestReport -p sqsbackend/
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: sqsbackend/build/reports/jacoco

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY }}
          coverage-reports: sqsbackend/build/reports/jacoco
