name: CI-Pipeline

on:
  push:

jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Permissionas
        run: chmod +x sqsbackend/gradlew 
        
      - name: Build with Gradle
        run: ./sqsbackend/gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: sqsbackend/build/libs
